### PR TITLE
doc: Shikanoin Heizou & Navia calls Traveler "partner"

### PR DESCRIPTION
**Pull request by xicri**

### CODE REVIEW

**Comment by xicri** [comment]
@Bill-Haku @SleepyAsh0191 I need your help with adding a translation for "partner" which is used by Shikanoin Heizou and Navia to call Traveler.

Shikanoin Heizou and Navia sometimes call Traveler "partner". The corresponding word in Simplified Chinese seems 搭档, but they sometimes add a prefix (?): 好 and 老.
I understand 好搭档 means a friendly and close partner, and 老搭档 means a partner since long ago. (I'm not sure why Navia called Traveler 老搭档 during the Archon Quest although they knew each other some days ago... while it is not related to this PR)

I wonder if I can only add 搭档 as the translation for "partner", or should I add all of 搭档, 好搭档, and 老搭档? Can you tell me your opinion?

Here are screenshots for reference:

Heizou English
Heizou Simplified Chinese
Navia 1 English
Navia 1 Simplified Chinese
Navia 2 English
Navia 2 Simplified Chinese
Navia 3 English
Navia 3 Simplified Chinese

In addition, I want to update `notesZh` field. I added [an update suggestion in English as a TODO comment](https://github.com/xicri/genshin-langdata/pull/168/files#diff-4b3f991d25b4c9c8e13d70b166e4ef465dc4f7d28ea8e4ba468f9e3efbb9f9d3R4014), so can you translate it to Chinese?
Please add a comment to this PR so that I can copy & paste your translation, or send me a PR to this branch (`doc-partner`) if you prefer to log your contribution in the Git commit history.

BTW, in the Japanese version, "partner" and (老/好)搭档 are translated as 相棒, and this Japanese translation is the same as Childe's "comrade" and 伙伴. That's why I added them as one word.

**Comment by Bill-Haku** [comment]
> I wonder if I can only add 搭档 as the translation for "partner", or should I add all of 搭档, 好搭档, and 老搭档? Can you tell me your opinion?

I would prefer only add 搭档 for the translation. 好搭档 and 老搭档 here seems like a localization that makes the whole chat sounds natural. 

Although as you have said, 老搭档 means a partner can mean a pair of partners since a long time, it can also means a pair of partners who have cooperated for a several times. Also this word can have a deeper meaning: suggesting that they are close partners, which is similar to 好搭档, in my opinion.

> In addition, I want to update notesZh field.

Yes, here's the translation.

公子、鹿野院平藏和娜维娅称呼旅行者的方式。在中文中，公子称呼旅行者为“伙伴”，但是鹿野院平藏和娜维娅称呼旅行者为“搭档”。在英文中，公子称呼旅行者为“comrade”，但是鹿野院平藏和娜维娅称呼旅行者为“partner”。在日语中，他们三人都称呼旅行者为“相棒“。

**Comment by xicri** [comment]
> > I wonder if I can only add 搭档 as the translation for "partner", or should I add all of 搭档, 好搭档, and 老搭档?
> 
> I would prefer only add 搭档 for the translation.

Thanks. OK, I will only add 搭档.

> Although as you have said, 老搭档 means a partner can mean a pair of partners since a long time, it can also means a pair of partners who have cooperated for a several times. Also this word can have a deeper meaning: suggesting that they are close partners, which is similar to 好搭档, in my opinion.

Got it. So Navia implied that she thinks she and the Traveler already had a close relationship like longtime partner at that time.

> > In addition, I want to update notesZh field.
> 
> Yes, here's the translation.
> 
> 公子、鹿野院平藏和娜维娅称呼旅行者的方式。在中文中，公子称呼旅行者为“伙伴”，但是鹿野院平藏和娜维娅称呼旅行者为“搭档”。在英文中，公子称呼旅行者为“comrade”，但是鹿野院平藏和娜维娅称呼旅行者为“partner”。在日语中，他们三人都称呼旅行者为“相棒“。

Thanks, I will add it!
Did you use `“` and `”` with any intent, or just Mac converted to it? If it is not intended, Can I replace them with `"` so that the sentences follows the style of other text in the Dictionary?

**Comment by Bill-Haku** [comment]
In a Chinese sentence we use `“”` rather than `"` . I think I also followed this principle in other places. Also, using `「」` is also acceptable in Chinese. If you don't want to use “” here, please replace them by 「」.

**Comment by xicri** [comment]
> In a Chinese sentence we use `“”` rather than `"` . I think I also followed this principle in other places.

Oh, then let's keep using `“”`.

I remember Mac automatically converts `"` to `“”` in Japanese environment when I used Mac although `"` is more popular in Japanese, so I misunderstood the same thing happened on your end.

**Pull request merged**
