### PR TITLE
Add Chinese Translation (2023.2.25)

### PR DESCRIPTION
**Pull request by SleepyAsh0191**

### CODE REVIEW

**Comment by xicri** [comment]
Oh, so quick! 😆 Thanks!
I'll review this tomorrow.

Snyk is raising an error, but you can safely ignore it.

**Review by xicri — APPROVED** [review]
Looks good!
I will also ask Bill to review later, then I will publish it.

**Comment by xicri** [comment]
@Bill-Haku As usual, can you review this PR?

**Review by Bill-Haku — APPROVED** [review]

**Comment by xicri** [comment]
@Bill-Haku Thanks!

@SleepyAsh0191 This update will be deployed in a few minutes.

**Pull request merged**
