### PR TITLE
Add Chinese Translation (2023.2.17)

### PR DESCRIPTION
**Pull request by SleepyAsh0191**

### CODE REVIEW

**Comment by xicri** [comment]
@SleepyAsh0191 Thanks!

@Bill-Haku Can you review this PR?

**Comment by Bill-Haku** [comment]
ok

**Review by Bill-Haku — APPROVED** [review]

**Review by xicri — APPROVED** [review]

**Comment by xicri** [comment]
@Bill-Haku Thanks for the review!

@SleepyAsh0191 I'll merge and release this PR.

**Comment by xicri** [comment]
@SleepyAsh0191 I will announce Chinese update on Twitter. Can I include your Twitter ID (wuhankun233) in that tweet?

**Comment by SleepyAsh0191** [comment]
> @SleepyAsh0191 I will make an update announcement on Twitter. Can I include your Twitter ID (wuhankun233) in that tweet?

Yes

**Pull request merged**
