### PR TITLE
Add Chinese Translation (2023.08.20)

### PR DESCRIPTION
**Pull request by SleepyAsh0191**

### CODE REVIEW

**Comment by SleepyAsh0191** [comment]
@xicri if you have time, plz see where is the error.

**Comment by xicri** [comment]
@SleepyAsh0191 The error is raised because there are two 悠古弦音的残章 in weapon-materials.json5.
Both Fragment of an Ancient Chord (悠久の弦の残章) and Chapter of an Ancient Chord (悠久の弦の断章) have the same Chinese translation: 悠古弦音的残章, but I guess Chinese translation of Chapter of an Ancient Chord is wrong.

**Comment by SleepyAsh0191** [comment]
> @SleepyAsh0191 The error is raised because there are two 悠古弦音的残章 in weapon-materials.json5. Both Fragment of an Ancient Chord (悠久の弦の残章) and Chapter of an Ancient Chord (悠久の弦の断章) have the same Chinese translation: 悠古弦音的残章, but I guess Chinese translation of Chapter of an Ancient Chord is wrong.

fixed

**Comment by xicri** [comment]
@SleepyAsh0191 Sorry for delay, I'll review.

@Bill-Haku Can you review this PR when you have time?

**Review by xicri — APPROVED** [review]

**Review by Bill-Haku — APPROVED** [review]

**Pull request merged**
