### PR TITLE
Extract some kinds of items to new tags

### PR DESCRIPTION
**Pull request by xicri**
This PR adds new tags:

- `drop`
- `drop-boss`
- `gemstone`
- `weapon-material`

This PR extracts the following types of items from items.json5 into new json5 files:

- drops -> drops.json5
- boss drops -> drops-boss.json5
- gemstones -> gemstones.json5
- specialties.json5
- talent-materials.json5
- weapon-materials.json5

### CODE REVIEW

**Comment by xicri** [comment]
@Bill-Haku @SleepyAsh0191 Can you help me with adding new tags?

I'm adding three new tags:

- `drop` ― Drops: Drop items from normal or elite enemies
- `drop-boss` ― Boss Drops: Drop items from bosses, including weekly bosses
- `gemstone` ― Gemstones: Gemstone materials used for character ascension
- `weapon-material` ― Weapon Ascension Materials

Can you translate 1. the tag name and 2. the page title for the tag pages (e.g. https://genshin-dictionary.com/ja/tags/talent-material/ )?

The tag names and page titles can be configured in [dataset/tags.json](https://github.com/xicri/genshin-langdata/blob/5e16e8e8bb416782291b8941d09b9ec9f1f5e496/dataset/tags.json#L262-L311).
Currently, Chinese tag names and page titles are "TBD".

Can you comment on the Chinese translations in this thread, or send a PR to this `doc/item-tags` branch if you want to log your contribution in the Git history?

If you both worked on the translation simultaneously, one of the translations would be wasted, so comment on this thread before you start working on the translation.

**Comment by Bill-Haku** [comment]
@SleepyAsh0191 I can do it this afternoon, if you can do it now, let me know

**Comment by SleepyAsh0191** [comment]
> @SleepyAsh0191 I can do it this afternoon, if you can do it now, let me know

wait, i can do it

**Comment by Bill-Haku** [comment]
okay let me do it

**Pull request merged**
