### PR TITLE
Add Chinese Translation (2023.3.10)

### PR DESCRIPTION
**Pull request by SleepyAsh0191**

### CODE REVIEW

**Comment by xicri** [comment]
@SleepyAsh0191 Thanks!

@Bill-Haku Can you review this PR as always?

**Review by Bill-Haku — DISMISSED** [review]

**Comment by xicri** [comment]
@SleepyAsh0191 Oops, CI is raising an error. This is probably caused by the changes I made today, so I'll take a look.

@Bill-Haku Translation data should not be affected by this error, so you don't have to review again after I fixed the issue.

**Comment by Bill-Haku** [comment]
got it

**Comment by xicri** [comment]
@SleepyAsh0191 I have fixed the problem in #103.
Can you rebase this branch with the main branch? (not merge because it creates unwanted merge commits and makes it difficult to handle the log.)
If you are not sure how to rebase, I will do it instead of you.

**Comment by SleepyAsh0191** [comment]
Sorry, I haven't tried git rebase before, thanks for your help

**Comment by SleepyAsh0191** [comment]
@xicri Sorry for ping, I'm busy at these day, so please do it instead of me, thanks.

**Comment by xicri** [comment]
@SleepyAsh0191 Sure.

Sorry, I was down yesterday and could not work on this PR... I will do it today.

**Review by xicri — APPROVED** [review]

**Comment by xicri** [comment]
@SleepyAsh0191 Thanks for waiting. It should be released in a few minutes.

**Pull request merged**
