### PR TITLE
Add new words for Natlan

### PR DESCRIPTION
**Pull request by xicri**
Add `natlan` tag for the upcoming Genshin Impact 5.0 release, and add character names introduced in the [teaser](https://www.youtube.com/watch?v=O2ATH__rtQo).

### CODE REVIEW

**Comment by xicri** [comment]
@Bill-Haku @SleepyAsh0191 If you have time, can you review f58a901 to check if the Chinese translations for the new characters are correct?

**Comment by xicri** [comment]
@yasuking0304 I have added only the Natlan characters by myself this time. Please take care not to add duplicate words :bow:

**Review by Bill-Haku — COMMENTED** [review]
I am not quite familiar with all these words right now, but it LGTM

**Comment by xicri** [comment]
@Bill-Haku Thanks!

**Pull request merged**
