### PR TITLE
Add Chinese Translation (2023.09.01) 

### PR DESCRIPTION
**Pull request by SleepyAsh0191**

### CODE REVIEW

**Comment by xicri** [comment]
@SleepyAsh0191 Just a confirmation, is this PR still WIP?

**Comment by SleepyAsh0191** [comment]
> @SleepyAsh0191 Just a confirmation, is this PR still WIP?

WIP (I'm taking break at sat and sunday)

**Comment by xicri** [comment]
@SleepyAsh0191 OK, thanks for confirmation.

**Comment by xicri** [comment]
@SleepyAsh0191 Oh, sorry, I missed it. I'm going to review this.
(When you mark the PRs ready for review, GitHub does not send notification emails to me... 😓)

@Bill-Haku Can you review this PR when you have time?

**Review by xicri — APPROVED** [review]

**Review by Bill-Haku — APPROVED** [review]

**Pull request merged**
