### PR TITLE
Add Chinese note

### PR DESCRIPTION
**Pull request by xicri**

### CODE REVIEW

**Comment by xicri** [comment]
@Bill-Haku @SleepyAsh0191 I have added `notesZh` property so that you can add notes for each word. Please add notes in Chinese if you have something worth adding.

For sample code, see the diff in this PR: https://github.com/xicri/genshin-langdata/pull/132/files#diff-b0d2da2626355b399d83ae849d4a4364a3ad358019a679d8554f9c679e282dc0

You can see how the note is shown on the following URLs:

- Chinese UI: https://genshin-dictionary.com/zh-CN/chihu-rock/
    - The content in `notesZh` is shown
- Japanese UI: https://genshin-dictionary.com/ja/chihu-rock/
    - The content in `notes` is shown
- English UI: https://genshin-dictionary.com/en/chihu-rock/
    - Note is not shown

The property name `notesZh` is a bit ugly, but as I plan to change the JSON format (#40), I keep this property name for now.

Policies to add notes:

- I think some contents in Japanese `notes` are worth translating into Chinese and English, so I want to ask you to translate such notes into Chinese.
    - However, not now. I plan to translate some Japanese `notes` into English, so I think it should be easier for you to translate them into Chinese after I add English notes. (But it does not mean you cannot directly translate from Japanese to Chinese)
- I don't think `notesZh` contents should be 100% translation from Japanese `notes`. I think the notes in each language can have different contents when they should.

Let me know if you have any ideas about these policies.

**Comment by Bill-Haku** [comment]
@xicri Thanks for your hard work. I agree with you that the notes part should not only include same contents in 3 languages for some common notes, but also notes specially prepared for users in different languages. Also, I suggest you to add some notes in Japanese for the etymology of certain words, especially the name of some characters and weapons which I found them very interesting and cultured, if you'd like to. For example, the name of weapon Rust (ja:弓蔵, zh:弓藏) comes from 「史記」: 飛鳥尽良弓蔵, which means hiding the good bows after all birds have been killed, further on, it means after you lose the value for the ruler, you may be killed or have a worse end. 

There's also many similar situations in Genshin's usages of word, how do you think of it?

**Comment by xicri** [comment]
@Bill-Haku 

> Also, I suggest you to add some notes in Japanese for the etymology of certain words, especially the name of some characters and weapons which I found them very interesting and cultured, if you'd like to.

That's nice! Let's add such topics when we can.

**Comment by Bill-Haku** [comment]
> That's nice! Let's add such topics when we can.

Thanks for you approval. Do you think it's necessary to add such notes for English?

**Comment by xicri** [comment]
I don't think it is **necessary** to add them, not only in English but also in Chinese and Japanese. I think we should add such topics only when we can quickly add them.

Because our primary value is to provide translations and there are many other websites which provides similar topics such as Fandom's Genshin Wiki, I don't think we should pay too much attentions to add such topics.

...I might misunderstand what you mean. If the above is not an answer for your comment, let me know🙏

**Comment by Bill-Haku** [comment]
Thanks for your opinion. I understand that you just want quick and brief information for some words. For more specific details, maybe we can provide a link to other websites such as wikipedia, fandom, etc.

**Comment by xicri** [comment]
Yes, that's right.

However, since this is our hobby project, we don't have to be too strict for this policy.

**Comment by Bill-Haku** [comment]
I've understood it. BTW I want to confirm that markdown is supported when editing in the json contents?

**Comment by xicri** [comment]
@Bill-Haku Yes, it supports markdown. You can add link by `[]()`.

(Maybe I need to write a document for contributors.)

**Comment by xicri** [comment]
Oops, no, `notesZh` doesn't support Markdown for now, while Japanese `notes` supports.
I forgot to support Markdown in `notesZh`.

But I *will* support Markdown in `notesZh`.

**Comment by Bill-Haku** [comment]
@xicri Thanks for supporting markdown.

@SleepyAsh0191 I am working on `characters.json5` and will make a PR after I finish this file. You can work on other files and let me know so that we will not do a duplicated work.

**Pull request merged**
