### PR TITLE
doc: correct Load -> Lord

### LINKED ISSUE #216: Fix typos: Lo"a"d to Lo"r"d
In the website, Lesser Lord Kusanali / 小吉祥草王 is mis-spelled as Lesser LOAD Kusanali, as shown in the screenshot below.

### PR DESCRIPTION
**Pull request by tjq21**
Closes #216

### CODE REVIEW

**Review by xicri — APPROVED** [review]
Thanks, looks good!

**Comment by xicri** [comment]
Something seems wrong and the CI is failing.
GitHub Actions failed to checkout this repository.

I'm investigating this problem.

**Comment by tjq21** [comment]
Thank you very much.
お疲れ様です。

**Comment by xicri** [comment]
Fixed by just restarting the CI process.

The fix would be deployed in a few minutes.
Thanks again for your contribution!

**Pull request merged**
